sudo: required
services:
  - docker

before_install:
  - docker build -t sunnykwok84/docker-react-2 -f Dockerfile.dev .

script:
  - docker run -e CI=true sunnykwok84/docker-react-2 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-app"
  env: "Dockerapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-964580344214"
  bucket_path: "docker-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
